version: '3.1'

services:
  auth-service:
    build:
      context: ./auth-service
    restart: always
    ports:
      - "8081:8080"

  gateway-service:
    build:
      context: ./gateway-service
    restart: always
    ports:
      - "8080:8080"

  session-service:
    build:
      context: ./session-service
    restart: always
    environment: 
      REDIS_ADDRES: "redis:6379"

  protected-service:
    build:
      context: ./protected-service
    restart: always    

#mongo-db
  mongo:
    image: mongo
    restart: always
    #ports: 
    #  - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#redis
  redis:
    container_name: redis
    hostname: redis
    image: redis
    #ports:
    #  - "6379:6379"
    restart: always

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8091:8081"