realms:
  -
    name: users
    redirectOnSuccess: "http://example.com:8080/user"
    authConfig:
      -
        type: userService
        parameters:
          endpoint: http://user-service:8081/user-service/v1/
          realm: users
      -
        type: textFile
        parameters:
          filePath: ./test/users.txt
      -
        type: oAuthGoogle
        parameters:
          clientID: cleint_id
          clientSecret: cleint_secret
  -
    name: staff
    redirectOnSuccess: "http://example.com:8080/user"
    authConfig:
      -
        type: textFile
        parameters:
          filePath: ./test/staff.txt
cookieDomains:
  - .example.com
  - localhost