realms:
  -
    name: users
    redirectOnSuccess: "http://example.com:8080/user"
    authConfig:
      -
        type: userService
        redirectOnSuccess: "http://example.com:8080/user"
        parameters:
          endpoint: http://user-service:8080/user-service/v1
          realm: users
  -
    name: staff
    redirectOnSuccess: "http://example.com:8080/user"
    authConfig:
      -
        type: userService
        parameters:
          endpoint: http://user-service:8080/user-service/v1
          realm: staff
cookieDomains:
  - .example.com
  - localhost
sessionID: BlazewallSession
endpoints:
  sessionService: http://session-service:8080/session-service/v1/sessions